server:
  port: 8085
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
   config:
    server: 
     git:
      uri: https://github.com/Satyamraj7667/Microservice-project-Config/tree/main
      clone-on-start : true